/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tugaspbolaelia;

/**
 *
 * @author Muhammad Faisal
 */
public class TugaLaelia extends javax.swing.JFrame {

    /**
     * Creates new form TugaLaelia
     */
    public TugaLaelia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgSegitiga = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Alas = new javax.swing.JLabel();
        Tinggi = new javax.swing.JLabel();
        btnHitungS = new javax.swing.JButton();
        txtLuasS = new javax.swing.JTextField();
        txtAlasS = new javax.swing.JTextField();
        txtTinggiS = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dlgLingkaran = new javax.swing.JDialog();
        dlgPersegi = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtSisi = new javax.swing.JTextField();
        btnHitungP = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtLuasP = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtJari2 = new javax.swing.JTextField();
        btnHitungL = new javax.swing.JButton();
        txtLuasL = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuSegitiga = new javax.swing.JMenuItem();
        mnuLingkaran = new javax.swing.JMenuItem();
        mnuPersegi = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        dlgSegitiga.setMinimumSize(new java.awt.Dimension(500, 400));
        dlgSegitiga.setPreferredSize(new java.awt.Dimension(500, 400));
        dlgSegitiga.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Muhammad Faisal\\Pictures\\chgc.jpg")); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(262, 229));
        jLabel1.setMinimumSize(new java.awt.Dimension(262, 229));
        dlgSegitiga.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        jLabel2.setText("RUMUS MENCARI LUAS SEGITIGA");
        dlgSegitiga.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        jLabel3.setText("Luas       :");
        dlgSegitiga.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, -1, -1));

        Alas.setText("Alas         :");
        dlgSegitiga.getContentPane().add(Alas, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, -1));

        Tinggi.setText("Tinggi      :");
        dlgSegitiga.getContentPane().add(Tinggi, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, -1, -1));

        btnHitungS.setText("Hitung Luas");
        btnHitungS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungSActionPerformed(evt);
            }
        });
        dlgSegitiga.getContentPane().add(btnHitungS, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 140, 30));

        txtLuasS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLuasSActionPerformed(evt);
            }
        });
        dlgSegitiga.getContentPane().add(txtLuasS, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 140, -1));

        txtAlasS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlasSActionPerformed(evt);
            }
        });
        dlgSegitiga.getContentPane().add(txtAlasS, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 60, -1));

        txtTinggiS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTinggiSActionPerformed(evt);
            }
        });
        dlgSegitiga.getContentPane().add(txtTinggiS, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 60, -1));

        jLabel4.setText("cm");
        dlgSegitiga.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, -1, -1));

        jLabel5.setText("cm");
        dlgSegitiga.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, -1, -1));

        dlgLingkaran.setMinimumSize(new java.awt.Dimension(400, 300));

        javax.swing.GroupLayout dlgLingkaranLayout = new javax.swing.GroupLayout(dlgLingkaran.getContentPane());
        dlgLingkaran.getContentPane().setLayout(dlgLingkaranLayout);
        dlgLingkaranLayout.setHorizontalGroup(
            dlgLingkaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        dlgLingkaranLayout.setVerticalGroup(
            dlgLingkaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        dlgPersegi.setMinimumSize(new java.awt.Dimension(893, 692));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Muhammad Faisal\\Pictures\\LuasPersegi.png")); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Sisi (s)    :");

        txtSisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSisiActionPerformed(evt);
            }
        });

        btnHitungP.setText("Hitung Luas");
        btnHitungP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungPActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Luas    :");

        txtLuasP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLuasPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dlgPersegiLayout = new javax.swing.GroupLayout(dlgPersegi.getContentPane());
        dlgPersegi.getContentPane().setLayout(dlgPersegiLayout);
        dlgPersegiLayout.setHorizontalGroup(
            dlgPersegiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgPersegiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dlgPersegiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(dlgPersegiLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(txtSisi, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnHitungP, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(dlgPersegiLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(txtLuasP)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        dlgPersegiLayout.setVerticalGroup(
            dlgPersegiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgPersegiLayout.createSequentialGroup()
                .addGroup(dlgPersegiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlgPersegiLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dlgPersegiLayout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addGroup(dlgPersegiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtSisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(btnHitungP)
                        .addGap(28, 28, 28)
                        .addGroup(dlgPersegiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtLuasP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(707, 435));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Muhammad Faisal\\Pictures\\luasLingkaran.jpg")); // NOI18N

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel7.setText("∏ = 3.14 /  22/7");

        jLabel8.setText("Jari - jari (r)    :");

        txtJari2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJari2ActionPerformed(evt);
            }
        });

        btnHitungL.setText("Hitung Luas");
        btnHitungL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungLActionPerformed(evt);
            }
        });

        txtLuasL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLuasLActionPerformed(evt);
            }
        });

        jLabel9.setText("Luas Lingkaran  :");

        jMenu1.setText("Aplikasi");

        mnuSegitiga.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        mnuSegitiga.setText("Luas Segitiga");
        mnuSegitiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSegitigaActionPerformed(evt);
            }
        });
        jMenu1.add(mnuSegitiga);

        mnuLingkaran.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        mnuLingkaran.setText("Luas Lingkaran");
        mnuLingkaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLingkaranActionPerformed(evt);
            }
        });
        jMenu1.add(mnuLingkaran);

        mnuPersegi.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        mnuPersegi.setText("Luas Persegi");
        mnuPersegi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPersegiActionPerformed(evt);
            }
        });
        jMenu1.add(mnuPersegi);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Bantuan");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtLuasL))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(txtJari2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 40, Short.MAX_VALUE))
                    .addComponent(btnHitungL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtJari2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnHitungL)
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtLuasL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuSegitigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSegitigaActionPerformed
        dlgSegitiga.setLocationRelativeTo(this);
        dlgSegitiga.setVisible(true);
    }//GEN-LAST:event_mnuSegitigaActionPerformed

    private void mnuLingkaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLingkaranActionPerformed
        dlgLingkaran.setLocationRelativeTo(this);
        dlgLingkaran.setVisible(true);
    }//GEN-LAST:event_mnuLingkaranActionPerformed

    private void mnuPersegiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPersegiActionPerformed
       dlgPersegi.setLocationRelativeTo(this);
       dlgPersegi.setVisible(true);
    }//GEN-LAST:event_mnuPersegiActionPerformed

    private void btnHitungSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungSActionPerformed
        double Tinggi = Double.parseDouble(txtTinggiS.getText());
        double Alas = Double.parseDouble(txtAlasS.getText());
        double Luas = ( (Alas * Tinggi ) * 0.5 );
        txtLuasS.setText(String.valueOf(Luas) + " cm2 ");
 
    }//GEN-LAST:event_btnHitungSActionPerformed

    private void txtAlasSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlasSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlasSActionPerformed

    private void txtLuasSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLuasSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLuasSActionPerformed

    private void txtTinggiSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTinggiSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTinggiSActionPerformed

    private void txtJari2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJari2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJari2ActionPerformed

    private void btnHitungLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungLActionPerformed
    double Jari2 = Double.parseDouble(txtJari2.getText());
    double Jari22 = (Jari2 * Jari2);
    double V = 3.14;
    double Luas_Lingkaran = Jari22 * V;
    txtLuasL.setText(String.valueOf(Luas_Lingkaran) + " cm2 ");
     }//GEN-LAST:event_btnHitungLActionPerformed

    private void txtLuasLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLuasLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLuasLActionPerformed

    private void txtSisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSisiActionPerformed

    private void btnHitungPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungPActionPerformed
        double sisi = Double.parseDouble(txtSisi.getText());
        double sisi2 = sisi * sisi;
        txtLuasP.setText(String.valueOf(sisi2) + " cm2 " );
    }//GEN-LAST:event_btnHitungPActionPerformed

    private void txtLuasPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLuasPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLuasPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TugaLaelia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TugaLaelia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TugaLaelia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TugaLaelia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TugaLaelia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alas;
    private javax.swing.JLabel Tinggi;
    private javax.swing.JButton btnHitungL;
    private javax.swing.JButton btnHitungP;
    private javax.swing.JButton btnHitungS;
    private javax.swing.JDialog dlgLingkaran;
    private javax.swing.JDialog dlgPersegi;
    private javax.swing.JDialog dlgSegitiga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuLingkaran;
    private javax.swing.JMenuItem mnuPersegi;
    private javax.swing.JMenuItem mnuSegitiga;
    private javax.swing.JTextField txtAlasS;
    private javax.swing.JTextField txtJari2;
    private javax.swing.JTextField txtLuasL;
    private javax.swing.JTextField txtLuasP;
    private javax.swing.JTextField txtLuasS;
    private javax.swing.JTextField txtSisi;
    private javax.swing.JTextField txtTinggiS;
    // End of variables declaration//GEN-END:variables
}
